### ISSUE TITLE
[BUG]: Account selected auto transforming to "account" while exiting child table.

### ISSUE THREAD

**Issue by forteqt** [kid1194/erpnext_expenses#7]
The account marked in yellow is transformed to "account"  and i am unable to select an expense account.

<img width="643" alt="image" src="https://github.com/kid1194/erpnext_expenses/assets/94223207/f49cd2ae-2180-480b-bb89-ee63271065ec">

**Comment by kid1194** [comment]
@forteqt  Hey bro..

Thank you for reporting this bug and sorry for the late reply..

Because of your post, I have made a lot if changes to the module and it is working without any problem, unless I have missed something..

So please give it another try and let me know if you face any problem..

Best regards..
